@echo off
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat
start "" cmd /c matrix.bat